/**
 * Constants for the Aeternity plugin
 */

export const AE_ACTIONS = {
  TRANSFER_AE: 'TRANSFER_AE',
  GENERATE_KEY_PAIR: 'GENERATE_KEY_PAIR',
  CALL_CONTRACT: 'CALL_CONTRACT',
  TIP_TELEGRAM_USER: 'TIP_TELEGRAM_USER',
  PROCESS_ADDRESS_REGISTRATION: 'PROCESS_ADDRESS_REGISTRATION',
  REGISTER_TELEGRAM_ADDRESS: 'REGISTER_TELEGRAM_ADDRESS',
  ANALYZE_CONTRIBUTION: 'ANALYZE_CONTRIBUTION',
}; 